# Generated by Django 3.2.6 on 2021-09-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_user_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
